mcu: Fix patch error for CS+ project file
Current patch occurs followng error:
  error: patch failed: hypervisor/obj/obj_1pe_atk2/cs_plus_renesas_rcar_s4.mtpj:1
  error: hypervisor/obj/obj_1pe_atk2/cs_plus_renesas_rcar_s4.mtpj: patch does not apply
This is due to different line endings of that project file.

And, this CS+ project file is not used in build process.
So, this patch removes it from patch file.

Reported-by: Yusuke Goda <yusuke.goda.sx@renesas.com>
Signed-off-by: Yuya Hamamachi <yuya.hamamachi.sx@renesas.com>